service: circleci-demo

provider:
  name: aws
  runtime: nodejs6.10
  region: eu-central-1

plugins:
  - serverless-offline

functions:
  generate:
    handler: handler.handler
    events:
      - http:
          path: generate
          method: get